### PR TITLE
ochuman dataset parser

### PR DESCRIPTION
**Pull request by FraPochetti**

### CODE REVIEW

**Comment by FraPochetti** [comment]
Do you know what is driving those issues? They seem quite cryptic to me.

**Comment by lgvaz** [comment]
@FraPochetti 

> Do you know what is driving those issues? They seem quite cryptic to me.

Not related to your changes I believe, same issues are happening on master as well

**Comment by FraPochetti** [comment]
How do you normally go to debug this kind of things?

**Comment by lgvaz** [comment]
The one failing with tests is related to [this](https://github.com/airctic/icevision/issues/572)

For the other one I'll just to try to build the docs locally and investigate what is happening. Probably a missing import somewhere? Idk, strange why it only fails on the docs and not on the tests (but I didn't even understood the issue completely yet :sweat_smile: )

**Review by lgvaz — CHANGES_REQUESTED** [review]
Alright alright! I just checked the errors and they are indeed not related to your PR so this is clear to go.

Just before we merge, can you add to the changelog that this new dataset was added? I'll then go and merge =)

**Comment by FraPochetti** [comment]
Done!

**Review by lgvaz — APPROVED** [review]
Perfect!

Thanks a lot for another PR Francesco! 🔥

**Pull request merged**
