### PR TITLE
Ochuman nb

### PR DESCRIPTION
**Pull request by FraPochetti**
Adding notebook

### CODE REVIEW

**Review by lgvaz — CHANGES_REQUESTED** [review]
Hi hi!

There is also a notebook on the root of the repo, should we delete that?

**Comment by ai-fast-track** [comment]
@FraPochetti LGTM. One minor change that I would do is to remove the `pip instal ...` **output** as it takes a lot of the screen real estate, and hide more important stuff that lays below it.

In the introduction, I would put this:

## OCHuman(Occluded Human) Dataset 

From the OCHuman repo:
> This dataset focus on heavily occluded human with comprehensive annotations including bounding-box, humans pose and instance mask. This dataset contains 13360 elaborately annotated human instances within 5081 images. With average 0.573 MaxIoU of each person, OCHuman is the most complex and challenging dataset related to human. Through this dataset, we want to emphasize occlusion as a challenging problem for researchers to study.

**Comment by FraPochetti** [comment]
Removed notebook in the root dir and addressed comment from Farid

**Review by lgvaz — APPROVED** [review]
green light to me

**Comment by lgvaz** [comment]
Another PR! Here we go!! Thanks a lot Francesco!

**Pull request merged**
